name: caldensmart
description: "Caldén Smart"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.17+16

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  fluttertoast: ^8.2.4
  path_provider: ^2.1.5
  flutter_blue_plus: ^1.33.4
  easy_refresh: ^3.4.0
  geolocator: ^10.1.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.2.3
  amplify_flutter: ^1.7.0
  amplify_auth_cognito: ^1.7.0
  mqtt_client: ^10.2.0
  provider: ^6.1.2
  firebase_messaging: ^14.7.20
  firebase_core: ^2.27.1
  aws_dynamodb_api: ^2.0.0
  dio: ^5.7.0
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.1.1
  mobile_scanner: ^5.2.1
  wifi_scan: ^0.4.1
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  day_night_time_picker: ^1.3.1
  image_picker: ^1.1.2
  upgrader: ^11.3.0
  cloud_firestore: ^4.17.5
  firebase_crashlytics: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.6
  flutter_native_splash: ^2.0.4

icons_launcher:
  image_path: "assets/LogoApp.png"
  platforms:
    ios:
      enable: true
      image_path: "assets/LogoApp.png"
    android:
      enable: true
      image_path: "assets/LogoApp.png"
      adaptive_background_image: "assets/Background.png"
      adaptive_foreground_image: "assets/DragonForeground.png"

flutter_native_splash:
  color: "#302b36"
  image: assets/DragonForeground.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/branch/Logo.png
    - assets/branch/dragon.gif
    - assets/branch/dragon.png
    - assets/DragonForeground.png
    - assets/branch/Foreground.png
    - assets/devices/015773.jpeg
    - assets/devices/020010.jpg
    - assets/devices/022000.jpg
    - assets/devices/027000.webp
    - assets/devices/027313.webp
    - assets/devices/050217.png
    - assets/misc/fondo.png
    - assets/misc/google.png
    - assets/branch/Logo_sitio.png
    - assets/misc/parteSuperior.png
    - assets/misc/persiana.jpg
    - assets/misc/millenium.png
    - assets/misc/millenium.gif
